### ISSUE TITLE
tox flake8 checker runs this plugin when checking

### ISSUE THREAD

**Issue by jakkdl** [Zac-HD/flake8-trio#12]
I just had a fun instance where I'd accidentally left a `breakpoint()` in my code when running `tox -e check` ... which led to flake8 crashing when trying to lint my code - since it's apparently including this plugin in it's checks. I looked at flake8 documentation if there was a way to disable a registered plugin, but somehow didn't see one, and the act of installing the plugin when creating the tox environment registers it in flake8.
`--disable=TRIO` looks like it just suppresses printing the errors, not disable it from running.

Feels like there should be an easy way of fixing this. But if not I think we can pass a flag parsed in `setup.py` by setting `install_command` in `tox.ini`, or use `setenv` to set an environment variable that's similarly parsed in `setup.py`.

**Comment by Zac-HD** [comment]
Eh, I think this is basically fine - it'll never pass when it should fail or vice-versa, and outright crashes tend to be easy to fix.

**Comment by jakkdl** [comment]
Yeah this is mostly just for me, I got hit by it again a bit later and took me a little while to figure out what happened. The biggest problem is that the error message (at least when doing `breakpoint()`) is supremely unhelpful w/ a huge double backtrace where the offending line is somewhere in the middle.
