### ISSUE TITLE
TRIO112 false alarm on strict_exception_groups

### ISSUE THREAD

**Issue by jakkdl** [Zac-HD/flake8-trio#138]
> > * **TRIO112**: nursery body with only a call to `nursery.start[_soon]` and not passing itself as a parameter can be replaced with a regular function call.
> 
> Ah, but _not_ if the nursery is passed `strict_exception_groups=`, because that would change exception types.

breaking out from #124 - in case the linter should also ignore those cases.

**Comment by Zac-HD** [comment]
Hmm, I think it's OK to raise a lint error (which can be noqa'd) since this is kinda weird, I just wouldn't want to automatically change the code when we could instead avoid breaking changes 😅
