### ISSUE TITLE
TRIO91X not disabled by default?

### ISSUE THREAD

**Issue by richardsheridan** [Zac-HD/flake8-trio#141]
I recently bumped flake8-trio on a whim and it is throwing TRIO910 into my CI:

https://github.com/richardsheridan/trio-parallel/actions/runs/4212170131/jobs/7311010067#step:6:15

These sections had been silenced before by `# noqa: TRIO107`. Ironically, I actually want the check *enabled* and explicitly silenced but this strikes me as a bug?

Some context:

- CPython 3.11
- flake8 6.0.0
- flake8-trio 23.2.5
- flake8 command: `flake8 --ignore=D,E,W,F401,F403,F405,F821,F822`
- flake8 config: in `setup.cfg` [below]

```ini
[flake8]
no-checkpoint-warning-decorators = pytest.fixture, asynccontextmanager
```

**Comment by jakkdl** [comment]
Ah, when you specify `--ignore` that will override the default-disabling of 910 (and any other codes disabled by default by flake8 or other plugins). If you use `--extend-ignore` instead then 910 will be disabled.

And yeah the code was renamed recently, so 107 is 910 and 108 is 911.

**Comment by richardsheridan** [comment]
Thanks for the tip! This fixes the issue. I copied that ignore line years ago from the trio source without taking time to understand the detailed semantics of it...
