### ISSUE TITLE
TRIO91X: Support comprehensions

### ISSUE THREAD

**Issue by jakkdl** [Zac-HD/flake8-trio#144]
Comprehensions are currently completely invisible to 91X, so these are currently misbehaving:
```python
async def foo_comprehension_1():
    [... for x in range(10) if await foo()]


# should error
async def foo_comprehension_2():
    [await foo() for x in range(10) if bar()]

# should not error
async def foo_comprehension_3():  # error: 0, "exit", Statement("function definition", lineno)
    [... async for x in bar()]
```

One cannot yield or return inside a comprehension though, so will require separate logic from loops - but it should be much simpler.
I'm pretty sure an async generator or `for` *cannot* be guaranteed to iterate at least once either, even with liberal use of starred expressions and the like.

https://peps.python.org/pep-0530/
https://libcst.readthedocs.io/en/latest/nodes.html#comprehensions

**Comment by Zac-HD** [comment]
> I'm pretty sure an async generator or for cannot be guaranteed to iterate at least once either, even with liberal use of starred expressions and the like.

Because it might be cancelled in the first checkpoint, right?  So while not iterating, it *does* at least have a checkpoint...

**Comment by jakkdl** [comment]
Ah, I meant in the sense of "does it make sense to call `iter_guaranteed_once`", but I didn't come up with any async expression that can be statically determined to always iter (unless you start listing library functions). But I now realize that it doesn't matter anyway since `async for` checkpoints on entry/exit anyway, and with no yields in the body, it will never matter whether it loops or not. So `async for` comprehensions can just be treated as a checkpoint, no matter the content. (non-async comprehensions with awaits in them still need some logic though)
