### ISSUE TITLE
Reduce `TRIO109` (`timeout` parameter) false-alarms by skipping decorated functions

### ISSUE THREAD

**Issue by Zac-HD** [Zac-HD/flake8-trio#24]
Turns out that many existing cases in our codebase are on some RPC method, test function, or similar, where a magic decorator causes code to run... elsewhere.  So just skipping this check for decorated functions would avoid a lot of false alarms 🙂

**Comment by jakkdl** [comment]
Ah, so disable if there's any decorator at all? No (configurable?) whitelist/blacklist?

**Comment by jakkdl** [comment]
I just realized I could change the notification settings for the repo to All Activity, had completely missed this one :upside_down_face: 
Maybe that will also give notifications on edits?

**Comment by Zac-HD** [comment]
Alas, I don't think there's *any* way to get notified on edits.  I'm just not using edits anymore though, new issues for anything new.
