### ISSUE TITLE
TRIO103: Check for guaranteed raise in loops?

### ISSUE THREAD

**Issue by jakkdl** [Zac-HD/flake8-trio#35]
Reading the readme, it says
> TRIO103: except BaseException and except trio.Cancelled with a code path that doesn't re-raise. Note that any raise statements in loops are ignored since it's tricky to parse loop flow with break, continue and/or the zero-iteration case.

But having implemented that logic with 107/108 I could extend that to 103 as well, likely without too much trouble.

**Comment by Zac-HD** [comment]
Since we've already got the logic for this, let's do it.  My understanding is that the only change here is that we'll stop emitting false-alarms on certain cases?

**Comment by jakkdl** [comment]
yep! e.g.
```python
while ...:
  raise
else:
  raise
```
is now an error but would be accepted

**Comment by jakkdl** [comment]
Didn't really reuse much logic from 107/108, other than applying reasoning I've already gone through once.
