### ISSUE TITLE
False alarm for TRIO107/108 when looping over nonempty static collections

### ISSUE THREAD

**Issue by Zac-HD** [Zac-HD/flake8-trio#41]
```python
import trio

async def foo():
    for _ in [1, 2, 3]:
        await trio.sleep(0)
```
```
$ flake8 example.py
example.py:3:1: TRIO107: exit from async function with no guaranteed checkpoint or exception since function definition on line 3
```

We can do better because static lists and tuples (and maybe some other collections?) have an `.elts` attribute in the AST which allows us to check whether they're nonempty.

**Comment by jakkdl** [comment]
oooh, me like!

**Comment by jakkdl** [comment]
Do you want to check for `while True` too?
e.g.
```python
while True:
  await foo()
  if ...:
    break
```
is guaranteed to checkpoint

**Comment by Zac-HD** [comment]
Might as well, for anything which `bool(ast.literal_eval(x))` can handle.
