### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by jakkdl** [Zac-HD/flake8-trio#62]
in https://github.com/Zac-HD/flake8-trio/commit/490a77585f40c19b0fb06d494d4317a6e505f444 you converted all files to CRLF line endings. Was this intentional?

It's not a huge problem for me, but it makes diffs on my local machine have ugly `^M`'s and apparently the remotes are stored with LF endings so whenever I try to diff or rebase against a remote branch it's a mess. So unless you don't mind I'd like to convert all files back to LF and add a `.gitattributes` file to hopefully stop it from happening in the future. But I'll wait with it until there's no open PR's to avoid merging nightmares.
If it was intentional I'll add a .gitattributes file indicating CRLF is preferred, and see if I can get git to play nicely with that on my local machine.

**Comment by Zac-HD** [comment]
Definitely an accident 😅, fix would be appreciated!
