### ISSUE TITLE
install_require flake8>=6.0?

### ISSUE THREAD

**Issue by jakkdl** [Zac-HD/flake8-trio#65]
Should we update `setup.py` to require flake8>=6.0, or modify tests so they can run on both <6.0 and >=6.0 - so we can make sure that code doesn't break on <6.0? Should be unlikely, but given that this one completely snuck up on me it's probably worth taking into account.

**Comment by Zac-HD** [comment]
I think it's worth keeping install-time support for older versions of flake8; how about we modify the tests and add a dimension to our test matrix?

**Comment by jakkdl** [comment]
Sounds reasonable, will fix :+1:
