### ISSUE TITLE
Handle spaces in config options

### ISSUE THREAD

**Issue by jakkdl** [Zac-HD/flake8-trio#89]
There's a bunch of different ways of handling spaces in comma_separated_list to fix `--trio200-blocking-calls`. Pending on what happens with https://github.com/PyCQA/flake8/issues/1771

* handle `['a', '->', 'b']` as well as `['a->b']` with fancy logic
* don't use `comma_separated_list` and write a custom action (more attractive if https://github.com/PyCQA/flake8/issues/1770 is fixed)
* Require users to wrap values in quotes or something. Though some quick testing looks like this doesn't help.
* Wait for it to be fixed upstream

**Comment by jakkdl** [comment]
Since 1771 was closed as invalid, this should likely be ignored for `--startable-in-context-manager` (since spaces aren't valid identifiers anyway), but `--trio200-blocking-calls` will need a custom `type` that handles this.

**Comment by Zac-HD** [comment]
Closed by #93.  (you need a keyword *per issue #*, annoyingly)
