### ISSUE TITLE
Add pre-commit bot to repo

### ISSUE THREAD

**Issue by jakkdl** [Zac-HD/flake8-trio#97]
@Zac-HD With #88 merged you need to add https://pre-commit.ci/ to the repository for the checks to actually run. High priority, although I have the hook installed locally so won't push code that doesn't pass the checks.

**Comment by Zac-HD** [comment]
I was thinking we'd just add `pre-commit run --all` to the Actions config, but could use pre-commit CI if preferred.

**Comment by jakkdl** [comment]
We mostly just miss out on getting pinged about hook updates automatically (auto-fixing PR's and the speed are w/e), which seems handy - but I haven't it run in CI on any repos I maintain so I don't have too strong of an opinion.

**Comment by Zac-HD** [comment]
Let's just go with Actions for now, I think running the update command occasionally will be easier than working across multiple platforms.

**Comment by jakkdl** [comment]
What do you see as issues with working across multiple platforms? Just curious of any downsides I'm not aware of

**Comment by Zac-HD** [comment]
Nothing major, just e.g. tiny UX papercuts from having two separate sites to check, click retry on, or whatever else.

**Comment by jakkdl** [comment]
Ah, sure. Don't check those often myself, but makes sense.
Looks like it's possible to homebrew auto-updates as well with github actions https://browniebroke.com/blog/gh-action-pre-commit-autoupdate/ - or I might at least set up a local hook that checks for updates.

**Comment by Zac-HD** [comment]
If you're going that far, check out the `tox -e deps` and pinning setup for `shed`; that plus a monthly Actions cronjob and update PR *ala* Hypothesis is nice to work with and pretty easy.
